#!/bin/sh

if [ -f /ZMOD ]; then
    /opt/config/mod/.shell/zremote.sh /opt/config/mod_data/plugins/timelapse/ffmpeg $@
else
    ARCH=$(uname -m)
    if [ "$ARCH" == "armv7l" ]; then
        export LD_LIBRARY_PATH=/opt/ffmpeg-4.0.2/lib:$LD_LIBRARY_PATH
        export LD_LIBRARY_PATH=/opt/x264/lib:$LD_LIBRARY_PATH
        /opt/ffmpeg-4.0.2/bin/ffmpeg $@
    else
        export LD_LIBRARY_PATH=/usr/prog/ffmpeg-4.0.2/lib:$LD_LIBRARY_PATH
        export LD_LIBRARY_PATH=/usr/prog/x264/lib:$LD_LIBRARY_PATH
        /usr/prog/ffmpeg-4.0.2/bin/ffmpeg $@
    fi
fi
